Fix: Docker installation if missing on the server

diff --git a/.github/workflows/deploy-staging.yml b/.github/workflows/deploy-staging.yml
--- a/.github/workflows/deploy-staging.yml
+++ b/.github/workflows/deploy-staging.yml
@@ -52,6 +52,16 @@ jobs:
           username: ${{ secrets.SERVER_USERNAME }}
           password: ${{ secrets.SERVER_PASSWORD }}
           script: |
+            if ! command -v docker &> /dev/null
+            then
+                echo "Docker not found! Installing..."
+                sudo apt update
+                sudo apt install -y docker.io
+                sudo systemctl enable --now docker
+                sudo usermod -aG docker $USER
+                echo "Docker installed successfully!"
+            fi
+
             docker network create --driver bridge image-network || true
 
             docker pull vighasks/todolist-docker-app:v1.0
